### ISSUE TITLE
how can l extract predict residual and SAD value?

### ISSUE THREAD

**Issue by shujishizcc** [jishnujayakumar/MV-Tractus#1]
excuse me ，how can i extract predict residual and SAD value? can you have good method ,thank you very much!

**Comment by jishnujayakumar** [comment]
Hi @shujishizcc. This is just a motion vector extraction tool. It doesn't and won't contain anything related to SAD value. But you can use the macroblock information like **source**, **src_x**, **src_y**, **dst_x**, **dst_y**, **block_width**, **block_height** and write a function that would serve the purpose.

**Comment by shujishizcc** [comment]
ok,thank you!
