### ISSUE TITLE
how to get referance frame of motion vector

### ISSUE THREAD

**Issue by NoharaMasato** [jishnujayakumar/MV-Tractus#10]
I want to get the information about reference frame of motion vector, in order to normalize mv.
I think, using FFmpeg, we cannot extract reference frame data. Because, there is a comment below in libavutil/motion_vector.h.
```
 /**
 26      * Where the current macroblock comes from; negative value when it comes
 27      * from the past, positive value when it comes from the future.
 28      * XXX: set exact relative ref frame reference instead of a +/- 1 "direction".
 29      */
 30     int32_t source;
```

I am searching the tool to get fully information of motion vector from compressed videos.
Could you give me some advice?

**Comment by jishnujayakumar** [comment]
We can actually. Source attribute shows from indicates the reference frame. Due to the nature of encoding it can be the previous one or the next one.

**Comment by sandra-vs-nair** [comment]
But it can be any of the previous frames or any of the future frames, right? It need not be the adjacent frames.
