### ISSUE TITLE
Can compile with binary compile file but not from compile command

### ISSUE THREAD

**Issue by fbordwell** [jishnujayakumar/MV-Tractus#11]
If I run ./compile I can successfully compile extract_mvs.c but if I run the command included in the compile_commands.txt file `gcc -o extract_mvs extract_mvs.c -lavcodec -lavformat -lavutil -lavdevice -lswresample -lswscale -L/opt/dev-tools-sources/ffmpeg/build/lib -I/opt/dev-tools-sources/ffmpeg/build/include -l json -w` 
I get the following error:
`ld: library not found for -ljson
clang: error: linker command failed with exit code 1 (use -v to see invocation)`
I am on MacOS.

**Comment by jishnujayakumar** [comment]
Hi @fbordwell, from the error, it seems that the JSON library is not installed on your system. Please try to install it and see if that works. I have not worked on macOS so I am afraid I can't help in that context. Feel free to revert back.
