### ISSUE TITLE
Runs extremely slow

### ISSUE THREAD

**Issue by backinabit** [jishnujayakumar/MV-Tractus#12]
It pegs one CPU core and gets only about 30 FPS. That's worse than software decoding the video on its own. MV extraction should have negligible CPU load at realtime framerate, or extremely high frame rate.

**Comment by jishnujayakumar** [comment]
@backinabit Good point. Frame rate depends upon the encoder. Hence whatever the encoder fixes as the frame rate, the same would be reflected from MV-Tractus.
