### ISSUE TITLE
Avoid all that library source

### ISSUE THREAD

**Issue by adrianmay** [jishnujayakumar/MV-Tractus#14]
Hi Jishnu,

I made a clone of your project (at least the two C targets, I don't do python) here: 
https://github.com/adrianmay/jishmo
demonstrating how to use CMake to make it really easy to link to standard libraries installed on your machine instead of pulling in all that source code. The commit history is intended to be instructive.

It means you have to keep up with changes to the libs (especially opencv who seem to move the furniture around every day just for the hell of it) but who wants to live in suspended animation? Right now the _with_frames target has a couple of deprecated functions in. I looked into fixing them but then my breakfast appeared and I don't really need that target for my purposes (spotting intruders on my cctv) anyway.

Hope that's helpful,
Adrian.

**Comment by jishnujayakumar** [comment]
Can you give a PR with your suggested changes?

**Comment by adrianmay** [comment]
If you take a look you'll see that it's not just a point and click thing.
