### ISSUE TITLE
DSO messing in command line

### ISSUE THREAD

**Issue by ZSoumia** [jishnujayakumar/MV-Tractus#15]
I had this error when running ./compile.

**Comment by jishnujayakumar** [comment]
Can you paste the exact stack trace?

**Comment by ZSoumia** [comment]
/usr/bin/ld: /opt/dev-tools-sources/ffmpeg/build/lib/libavcodec.a(vaapi_decode.o): reference to undefined symbol « vaCreateConfig »
//usr/lib/x86_64-linux-gnu/libva.so.2 : error when adding  symboles : DSO missing in command line 
collect2: error: ld returned 1 exit status
/usr/bin/ld: /opt/dev-tools-sources/ffmpeg/build/lib/libavcodec.a(vaapi_decode.o): reference to undefined symbol « vaCreateConfig »
//usr/lib/x86_64-linux-gnu/libva.so.2 :error when adding  symboles: missing in command line 
collect2: error: ld returned 1 exit status

**Comment by jishnujayakumar** [comment]
libva.so link is not made correctly. Please try to link it properly. It can help. Please comment with the results.
