### ISSUE TITLE
libavcodec/avcodec.h not found

### ISSUE THREAD

**Issue by prashantbodh099** [jishnujayakumar/MV-Tractus#16]
Hello,
I have successfully cloned your repository and also installed FFmpeg using ./install_ffmpeg.sh command.
But when I am trying to compile, it is showing some errors. 

![error_compile](https://user-images.githubusercontent.com/46018212/84893072-466b5180-b0bc-11ea-8c6d-369b6ce36df3.png)

`
In file included from extract_mvs.c:29:
include/libavformat/avformat.h:319:10: fatal error: libavcodec/avcodec.h: No such file or directory
  319 | #include "libavcodec/avcodec.h"
compilation terminated.
In file included from extract_mvs_with_frames.c:29:
include/libavformat/avformat.h:319:10: fatal error: libavcodec/avcodec.h: No such file or directory
  319 | #include "libavcodec/avcodec.h"
compilation terminated.
`

[](url)

**Comment by jishnujayakumar** [comment]
It seems that the corresponding libs are missing from your system. Installing them can help.

**Comment by prashantbodh099** [comment]
Okay, Then how to make them install and available to include them. I need more assistance on the same.

**Comment by jishnujayakumar** [comment]
You will get your answer in the install script itself.

**Comment by jishnujayakumar** [comment]
If the problem has been resolved, I will close the issue by EOD. Please comment.

**Comment by jason-richards** [comment]
Yes thank you!
