### ISSUE TITLE
Motion Vectors

### ISSUE THREAD

**Issue by jason-richards** [jishnujayakumar/MV-Tractus#18]
Why are the motion vectors listed twice in output file?

**Comment by jishnujayakumar** [comment]
> Why are the motion vectors listed twice in output file?

Can you share a screenshot please?

**Comment by jason-richards** [comment]
Just in your video; src_x, dst_x are listed twice in json

**Comment by jishnujayakumar** [comment]
Yeah very good point. The issue has been resolved in #13 
PS: The video was made before bug rectification.
