### ISSUE TITLE
extract_mvs Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by Abby-Wu** [jishnujayakumar/MV-Tractus#20]
Thank you for your work which is really important for me. However, I failed to extract MVs. The error is Segmentation fault (core dumped). My operation is that ./extract_mvs_with_frames output/video/1.264 or ./extract_mvs_with_frames output/video/v_ApplyEyeMakeup_g01_c01.avi .  These path are video file path.

**Comment by Abby-Wu** [comment]
Thank you again for your work. The previous problems have been solved. Recently, I have a new task, which need extract MVs and save them as images. What should I  do about this task? Thank you.

**Comment by peaceful29** [comment]
@Abby-Wu  I have the same problem. Can you help me how to fix it :(

**Comment by jishnujayakumar** [comment]
> Thank you again for your work. The previous problems have been solved. Recently, I have a new task, which need extract MVs and save them as images. What should I  do about this task? Thank you.

You can try using extract_mvs_with_frames.c
