### ISSUE TITLE
Meaning of the Json file

### ISSUE THREAD

**Issue by SIJIEJI** [jishnujayakumar/MV-Tractus#21]
Hi, Thank you for providing such a wonderful tool.  May I know the fields of the generated JSON file mean? Say source/ width/ height and etc. I google it and try understanding by myself but I fail.

	{
		"source" : 1,
		"width" : 8,
		"height" : 8,
		"src_x" : 172,
		"src_y" : 604,
		"dst_x" : 158,
		"dst_y" : 627,
		"dx" : -14,
		"dy" : 23
	}

Thanks a lot!

**Comment by wabisabit** [comment]
You can find the meaning of most here: https://ffmpeg.org/doxygen/3.1/motion__vector_8h_source.html
`dx` and `dy` are the distance from source to destination.

**Comment by SIJIEJI** [comment]
> You can find the meaning of most here: https://ffmpeg.org/doxygen/3.1/motion__vector_8h_source.html
> `dx` and `dy` are the distance from source to destination.

Thanks a lot!!
