### ISSUE TITLE
Error in compilation 

### ISSUE THREAD

**Issue by sak25** [jishnujayakumar/MV-Tractus#22]
I am getting the following error on compilation.Kindly help
![20201119_231158](https://user-images.githubusercontent.com/49688258/99703238-e0488780-2abc-11eb-8520-55691a558f93.jpg)

**Comment by jishnujayakumar** [comment]
I am sorry. I am not getting enough time to put into this project so I am afraid I can't help you at this point in time. But looking at the screenshot, it seems that the new FFMPEG codebase is causing the issue. One more person had the same problem. I think he had solved it by installing an appropriate version of the same. Hope this helps. Unfortunately, I don't remember the exact version. If you have any queries regarding the same, feel free to ask https://www.linkedin.com/in/arjjun-sathish-86ab3044/, I think that he has solved a similar issue.

**Comment by sak25** [comment]
Is it possible to extract motion vectors at 8*8 or 4*4 level as well. Currently its at 16*16 level.

**Comment by ColdCodeCool** [comment]
@sak25  so, did you solve your problem? I have had the same problem as you.

**Comment by sak25** [comment]
> @sak25 so, did you solve your problem? I have had the same problem as you.

It's a temporary debug, just change the name of the structure which is causing the error.

**Comment by alanzyt311** [comment]
@sak25 Hi, sorry to bother you. I met the same problem as you. You said that change the name of the structure is causing the error. So you mean change a name for the `AVPacketList`?

However, when I change its name, new errors pop up. Could you give me some advice on how you solve it before? Thx a lot!
