### ISSUE TITLE
Vectors at different levels

### ISSUE THREAD

**Issue by sak25** [jishnujayakumar/MV-Tractus#23]
Is it possible to extract motion vectors at 8x8 or 4x4 level as well. Currently its at 16x16 level.

**Comment by jishnujayakumar** [comment]
It's possible. But I think it depends on the encoder. Since mv-tractus decodes the stream, it has no control over the block size. Once the motion-vec info is obtained only it can be inferred. I hope that this answered your query.

**Comment by sak25** [comment]
> It's possible. But I think it depends on the encoder. Since mv-tractus decodes the stream, it has no control over the block size. Once the motion-vec info is obtained only it can be inferred. I hope that this answered your query.

Thabks a lot.Exactly, but since you mention for h.264 encoded format, which has 16x16 pixel level, I was a bit confused. It would work for hevc encoded video formats as well then right?

**Comment by jishnujayakumar** [comment]
I haven't tried MVT that way. So I am afraid I can't help in that context.
