### ISSUE TITLE
Can not compile -> libavcodec/avocdec.h not found

### ISSUE THREAD

**Issue by mullanptr** [jishnujayakumar/MV-Tractus#4]
Hi,
I can not compile.
The command ('./compile') throws this error:

```
$> ./compile 
In file included from extract_mvs.c:29:0:
include/libavformat/avformat.h:319:32: fatal error: libavcodec/avcodec.h: No such file or directory
compilation terminated.

```
When looking online for this error, I only find one thread concerning this error in general [1].
There it is suggested to have a recent ffmpeg version; I updated ffmpeg to 4.1; Didn't help, though...

Any ideas?

[1] https://github.com/leandromoreira/ffmpeg-libav-tutorial/issues/15

**Comment by mullanptr** [comment]
This fixed it:
`sudo apt-get install libavformat-dev`

But, then gave me:
```
$> ./compile 
/usr/bin/ld: cannot find -lavdevice
/usr/bin/ld: cannot find -ljson
collect2: error: ld returned 1 exit status

```

How to fix that, now... 
Ahhhhhhhhhh

**Comment by jishnujayakumar** [comment]
Hi @mullanptr, 

If you have installed FFmpeg correctly then this error should not crop up. Check the installation.

Else try manually installing the missing libs from Ubuntu universe.

Hope that helps.

**Comment by mullanptr** [comment]
I now set up an Ubuntu 18.04 in a virtual machine.
Run your installation-scripts -> Bumped into same errors.

So as it is a mint fresh set up Ubuntu installation, I can not see any problems I could have made during set up...

**Comment by jishnujayakumar** [comment]
We had also run into the same problem. It seems that the packages offered by Ub18.04 are broken. Hence we rolled back to Ub16.04. Even 17.04 couldn't run it. As of now Ub16.04 is the best one to go with.
