### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by marius0210** [jishnujayakumar/MV-Tractus#5]
Hi, I tried to compile and I have this error: /usr/bin/x86_64-linux-gnu-ld: cannot find -ljson
collect2: error: ld returned 1 exit status
I tried to install this package but did not solve the problem: sudo apt-get install libjson-glib-dev

**Comment by jishnujayakumar** [comment]
Hi @ marius0210, 
Try using the compile command here.
https://github.com/jishnujayakumar/MV-Tractus/blob/master/compile

**Comment by marius0210** [comment]
Thanks @jishnujayakumar, I complied the program.
But now when I have this error from ./extract_mvs
root@mb-ThinkPad-L512:/home/mb/MV-Tractus# ./extract_mvs /home/mb/test.mp4 
bash: ./extract_mvs: No such file or directory

**Comment by jishnujayakumar** [comment]
Please refer #2

**Comment by marius0210** [comment]
I tried all the solution but nothing I have the same problem. You made this project on Ubuntu 16.04 and -ljson how do you installed?
I think that your last commit in compiler don't work properly.

**Comment by jishnujayakumar** [comment]
We have tested this in 5-6 systems and they are working really fine. Please follow the instructions carefully in the README. I am sorry but I think there is something wrong with your setup or some library is not linked properly.
