### ISSUE TITLE
Plot Motion Vector

### ISSUE THREAD

**Issue by sebawsky** [jishnujayakumar/MV-Tractus#7]
I managed to extract the Motion Vector from a video but I need to graph the information that I extract. You have a method to show the data as the image or if it is possible if you can express the following variables that are in the json files:

dst_x
dst_y
dx
dy
height
source
src_x
src_y
width

THANKS!!!!

**Comment by jishnujayakumar** [comment]
If I understand correctly, by graphing you mean to show the MVs properly. For this you can use FFPlay itself. It plots the MVs on to the video itself.
`ffplay -flags2 +export_mvs input.mp4 -vf codecview=mv=pf+bf+bb`
